
const companies = [
    {
      name: 'Wisedoc, Inc.',
      position: 'Frontend Developer',
      location: 'India (Remote)',
      responsibilities: ['Develop user interfaces', 'Collaborate with designers'],
      qualifications: ['HTML', 'CSS', 'JavaScript', 'React or Vue.js'],
      benefits: ['Competitive salary', 'Flexible remote work', 'Health insurance'],
    },
    {
      name: 'TechGenius Solutions',
      position: 'Full Stack Developer',
      location: 'United States (On-site)',
      responsibilities: ['Design and implement software solutions', 'Collaborate with cross-functional teams'],
      qualifications: ['Web development technologies', 'Backend frameworks (e.g., Node.js)'],
      benefits: ['401(k) plan', 'Health and dental coverage', 'Professional development opportunities'],
    },
    {
      name: 'InnovateTech Labs',
      position: 'Data Scientist',
      location: 'Singapore (Remote)',
      responsibilities: ['Analyzing and interpreting complex data sets', 'Developing custom data models'],
      qualifications: ['Strong statistical and programming skills', 'Experience with machine learning frameworks'],
      benefits: ['Remote work options', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'CodeCrafters Ltd.',
      position: 'UX/UI Designer',
      location: 'Canada (Remote)',
      responsibilities: ['Create visually appealing user interfaces', 'Collaborate with product managers'],
      qualifications: ['Proven experience in UX/UI design', 'Familiarity with design tools (e.g., Sketch, Figma)'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Generous vacation policy'],
    },
    // Add 16 more companies here...
    {
      name: 'WebMasters Co.',
      position: 'SEO Specialist',
      location: 'Australia (On-site)',
      responsibilities: ['Optimize website content for search engines', 'Analyze and implement SEO strategies'],
      qualifications: ['Experience in SEO optimization', 'Familiarity with SEO tools'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'SoftInnovate Solutions',
      position: 'Software Engineer',
      location: 'Germany (Remote)',
      responsibilities: ['Design and implement software solutions', 'Collaborate with development teams'],
      qualifications: ['Proficiency in programming languages', 'Experience with software development methodologies'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'EcoTech Innovations',
      position: 'Environmental Analyst',
      location: 'Brazil (On-site)',
      responsibilities: ['Analyze environmental data', 'Contribute to sustainability initiatives'],
      qualifications: ['Degree in Environmental Science', 'Experience in data analysis'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'FinTech Solutions Ltd.',
      position: 'Financial Analyst',
      location: 'United Kingdom (Remote)',
      responsibilities: ['Analyze financial data', 'Contribute to financial planning'],
      qualifications: ['Degree in Finance or related field', 'Experience in financial analysis'],
      benefits: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'MedTech Innovators',
      position: 'Biomedical Engineer',
      location: 'Spain (On-site)',
      responsibilities: ['Design and develop medical devices', 'Collaborate with healthcare professionals'],
      qualifications: ['Degree in Biomedical Engineering', 'Experience in medical device development'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'FoodieTech Solutions',
      position: 'Mobile App Developer',
      location: 'France (Remote)',
      responsibilities: ['Develop mobile applications', 'Collaborate with UX/UI designers'],
      qualifications: ['Proficiency in mobile app development', 'Experience with iOS and Android platforms'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'AI Innovations Co.',
      position: 'Machine Learning Engineer',
      location: 'South Korea (On-site)',
      responsibilities: ['Design and implement machine learning models', 'Collaborate with data scientists'],
      qualifications: ['Degree in Computer Science or related field', 'Experience in machine learning'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'GreenEnergy Innovate',
      position: 'Renewable Energy Analyst',
      location: 'Netherlands (Remote)',
      responsibilities: ['Analyze renewable energy data', 'Contribute to sustainable energy projects'],
      qualifications: ['Degree in Renewable Energy or related field', 'Experience in energy analysis'],
      benefits: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'SpaceTech Explorations',
      position: 'Aerospace Engineer',
      location: 'Sweden (On-site)',
      responsibilities: ['Design and develop aerospace systems', 'Collaborate with space agencies'],
      qualifications: ['Degree in Aerospace Engineering', 'Experience in aerospace systems design'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'RoboTech Solutions',
      position: 'Robotics Engineer',
      location: 'Italy (On-site)',
      responsibilities: ['Design and develop robotic systems', 'Collaborate with engineering teams'],
      qualifications: ['Degree in Robotics or related field', 'Experience in robotics engineering'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'HealthTech Solutions',
      position: 'Health Informatics Specialist',
      location: 'Denmark (On-site)',
      responsibilities: ['Analyze health data', 'Contribute to health informatics projects'],
      qualifications: ['Degree in Health Informatics or related field', 'Experience in health data analysis'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      name: 'CyberSec Innovations',
      position: 'Cybersecurity Analyst',
      location: 'Switzerland (Remote)',
      responsibilities: ['Analyze and implement cybersecurity measures', 'Collaborate with IT teams'],
      qualifications: ['Degree in Cybersecurity or related field', 'Experience in cybersecurity analysis'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'Blockchain Innovators',
      position: 'Blockchain Developer',
      location: 'Norway (Remote)',
      responsibilities: ['Develop blockchain applications', 'Collaborate with blockchain experts'],
      qualifications: ['Proficiency in blockchain development', 'Experience with blockchain frameworks'],
      benefits: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'EdTech Innovate',
      position: 'Educational Technologist',
      location: 'Finland (Remote)',
      responsibilities: ['Develop educational technology solutions', 'Collaborate with educators'],
      qualifications: ['Proficiency in educational technology', 'Experience in edtech development'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      name: 'CleanTech Solutions',
      position: 'Environmental Engineer',
      location: 'Iceland (On-site)',
      responsibilities: ['Design and implement environmental solutions', 'Collaborate with environmental scientists'],
      qualifications: ['Degree in Environmental Engineering or related field', 'Experience in environmental engineering'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
  ];
  
export default companies;  