const itCompanies = [
    
    {
      id:1,
      name: "Microsoft",
      followers: "10M followers",
      logoUrl: "https://www.shutterstock.com/image-photo/haifa-israel-march-2-2018-260nw-1041740725.jpg",
      industry: "Technology",
      foundedYear: 1975,
      description: "Microsoft Corporation is an American multinational technology company...",
      location: "Redmond, Washington, USA",
      revenue: "$168.1 billion (2021)",
      website: "https://www.microsoft.com",
      ceo: "Satya Nadella",
      employees: 181000,
      products: ["Windows", "Office", "Azure"],
      stockSymbol: "MSFT",
      headquarters: "One Microsoft Way, Redmond, WA 98052-6399, USA",
      marketCap: "$2.5 trillion (2021)",
      competitors: ["Apple", "Google", "Amazon"],
      awards: ["Fortune 500", "World's Most Admired Companies"],
      socialMedia: {
          twitter: "https://twitter.com/Microsoft",
          linkedIn: "https://www.linkedin.com/company/microsoft",
          facebook: "https://www.facebook.com/Microsoft",
      },
      contactEmail: "contact@microsoft.com",
      customerSupport: {
          phone: "+1 (800) MICROSOFT",
          chat: "https://support.microsoft.com/en-us/contactus",
      },
      partnerships: ["NASA", "UNICEF", "Accenture"],
      posts: [
          {
              content: "Exciting new product launch!",
              imageUrl: "https://media.licdn.com/dms/image/D4D12AQHTV4uW-Gcmxg/article-cover_image-shrink_600_2000/0/1698294262321?e=2147483647&v=beta&t=ozDvhNGw92TqPvQT6R8McrGIttpXYKRxjKnsnRvJfpE",
          },
          {
              content: "Join us at the tech conference!",
              imageUrl: "https://i.ytimg.com/vi/_5Ri3X0DFok/maxresdefault.jpg",
          },
      ],
      shortDescription: "Microsoft is a global technology leader, known for its innovative products and solutions. With a rich history dating back to 1975, the company continues to shape the future of technology.",
  },
  {
    id:2,
    name: "Intel",
    followers: "10M followers",
    logoUrl: "https://www.datacenterknowledge.com/sites/datacenterknowledge.com/files/styles/article_featured_retina/public/2J8DPRY.jpg?itok=rCCZCDld",
    industry: "Technology",
    foundedYear: 1975,
    description: "Microsoft Corporation is an American multinational technology company. It develops, licenses, and sells computer software, consumer electronics, and other personal computing and communications services.",
    location: "Redmond, Washington, USA",
    revenue: "$168.1 billion (2021)",
    website: "https://www.microsoft.com",
    ceo: "Satya Nadella",
    employees: 181000,
    products: ["Windows", "Office", "Azure"],
    stockSymbol: "MSFT",
    headquarters: "One Microsoft Way, Redmond, WA 98052-6399, USA",
    marketCap: "$2.5 trillion (2021)",
    competitors: ["Apple", "Google", "Amazon"],
    awards: ["Fortune 500", "World's Most Admired Companies"],
    socialMedia: {
        twitter: "https://twitter.com/Microsoft",
        linkedIn: "https://www.linkedin.com/company/microsoft",
        facebook: "https://www.facebook.com/Microsoft",
    },
    contactEmail: "contact@microsoft.com",
    customerSupport: {
        phone: "+1 (800) MICROSOFT",
        chat: "https://support.microsoft.com/en-us/contactus",
    },
    partnerships: ["NASA", "UNICEF", "Accenture"],
    posts: [
        {
            content: "Exciting new product launch!",
            imageUrl: "",
        },
        {
            content: "Join us at the tech conference!",
            imageUrl: "",
        },
    ],
    shortDescription: "Microsoft is a global technology leader, known for its innovative products and solutions. With a rich history dating back to 1975, the company continues to shape the future of technology.",
},
{
    id:3,
    name: "Google",
    followers: "15M followers",
    logoUrl: "https://media.thekashmirmonitor.net/wp-content/uploads/2022/04/google.jpg",
    industry: "Technology",
    foundedYear: 1998,
    description: "Google LLC is an American multinational technology company that specializes in Internet-related services and products. Google's mission is to organize the world's information and make it universally accessible and useful.",
    location: "Mountain View, California, USA",
    revenue: "$183 billion (2021)",
    website: "https://www.google.com",
    ceo: "Sundar Pichai",
    employees: 150000,
    products: ["Search", "Maps", "YouTube", "Android"],
    stockSymbol: "GOOGL",
    headquarters: "1600 Amphitheatre Parkway, Mountain View, CA 94043, USA",
    marketCap: "$2 trillion (2021)",
    competitors: ["Microsoft", "Apple", "Amazon"],
    awards: ["Best Place to Work", "Top Innovator"],
    socialMedia: {
        twitter: "https://twitter.com/Google",
        linkedIn: "https://www.linkedin.com/company/google",
        facebook: "https://www.facebook.com/Google",
    },
    contactEmail: "contact@google.com",
    customerSupport: {
        phone: "+1 (650) 253-0000",
        chat: "https://support.google.com/",
    },
    partnerships: ["NASA", "UNESCO", "Tesla"],
    posts: [
        {
            content: "Discover the latest in search technology!",
            imageUrl: ""        },
        {
            content: "Join us for a virtual event!",
            imageUrl: ""        },
    ],
    shortDescription: "Google is a global technology giant, renowned for its search engine and diverse portfolio of products. Founded in 1998, Google continues to innovate and shape the digital landscape.",
},
{
    id:4,
    name: "Apple",
    followers: "20M followers",
    logoUrl: "https://akm-img-a-in.tosshub.com/aajtak/images/story/202002/apple_wwdc_main_1582783356_749x421.jpeg?size=948:533",
    industry: "Technology",
    foundedYear: 1976,
    description: "Apple Inc. is an American multinational technology company that designs, manufactures, and markets consumer electronics, computer software, and online services. Apple is known for its innovative hardware and software products.",
    location: "Cupertino, California, USA",
    revenue: "$365 billion (2021)",
    website: "https://www.apple.com",
    ceo: "Tim Cook",
    employees: 154000,
    products: ["iPhone", "Mac", "iPad", "Apple Watch"],
    stockSymbol: "AAPL",
    headquarters: "One Apple Park Way, Cupertino, CA 95014, USA",
    marketCap: "$2.5 trillion (2021)",
    competitors: ["Microsoft", "Google", "Samsung"],
    awards: ["Innovation Award", "Best Design"],
    socialMedia: {
        twitter: "https://twitter.com/Apple",
        linkedIn: "https://www.linkedin.com/company/apple",
        facebook: "https://www.facebook.com/Apple",
    },
    contactEmail: "contact@apple.com",
    customerSupport: {
        phone: "+1 (800) MY-APPLE",
        chat: "https://support.apple.com/",
    },
    partnerships: ["Nike", "Disney", "IBM"],
    posts: [
        {
            content: "Introducing the latest iPhone!",
            imageUrl: ""       },
        {
            content: "Join the Apple Developer community!",
            imageUrl: ""       },
    ],
    shortDescription: "Apple is a leading technology company known for its iconic products and commitment to design excellence. Founded in 1976, Apple continues to set industry standards and push the boundaries of innovation.",
},
{
  id:5,
    name: "Amazon",
    followers: "18M followers",
    logoUrl: "https://static.toiimg.com/thumb/msid-95742376,width-1280,height-720,resizemode-4/95742376.jpg",
    industry: "E-commerce",
    foundedYear: 1994,
    description: "Amazon.com, Inc. is an American multinational technology company focused on e-commerce, cloud computing, digital streaming, artificial intelligence, and more. Amazon is one of the world's largest and most influential companies.",
    location: "Seattle, Washington, USA",
    revenue: "$386 billion (2021)",
    website: "https://www.amazon.com",
    ceo: "Andy Jassy",
    employees: 1200000,
    products: ["Amazon Prime", "AWS", "Kindle", "Echo"],
    stockSymbol: "AMZN",
    headquarters: "410 Terry Ave N, Seattle, WA 98109, USA",
    marketCap: "$1.7 trillion (2021)",
    competitors: ["Alibaba", "Walmart", "Google"],
    awards: ["Best Employer", "Top Innovator"],
    socialMedia: {
        twitter: "https://twitter.com/amazon",
        linkedIn: "https://www.linkedin.com/company/amazon",
        facebook: "https://www.facebook.com/Amazon",
    },
    contactEmail: "contact@amazon.com",
    customerSupport: {
        phone: "+1 (888) 280-4331",
        chat: "https://www.amazon.com/gp/help/customer/contact-us",
    },
    partnerships: ["NASA", "UNHCR", "St. Jude Children's Research Hospital"],
    posts: [
        {
            content: "Discover exclusive deals on Prime Day!",
            imageUrl: ""        },
        {
            content: "Join our sustainability initiative!",
            imageUrl: ""        },
    ],
    shortDescription: "Amazon is a global e-commerce and technology giant, known for its diverse range of products and services. With a customer-centric approach, Amazon continues to redefine the way people shop and consume digital content.",
},
{
  id:6,
  name: "IBM",
  followers: "8M followers",
  logoUrl: "https://media.istockphoto.com/id/1319657811/photo/exterior-view-of-the-french-headquarters-of-ibm-bois-colombes-france.jpg?s=612x612&w=0&k=20&c=-Nav8ryjF-RdEmGdC2arPttYTfemEy7XNpKfrmYaI_w=",
  industry: "Information Technology",
  foundedYear: 1911,
  description: "International Business Machines Corporation (IBM) is an American multinational technology and consulting company. IBM is one of the world's oldest and largest IT companies, offering a range of technology and business services.",
  location: "Armonk, New York, USA",
  revenue: "$73.6 billion (2021)",
  website: "https://www.ibm.com",
  ceo: "Arvind Krishna",
  employees: 352600,
  products: ["IBM Cloud", "Watson", "Power Systems"],
  stockSymbol: "IBM",
  headquarters: "1 New Orchard Road, Armonk, NY 10504-1722, USA",
  marketCap: "$120 billion (2021)",
  competitors: ["Microsoft", "Oracle", "SAP"],
  awards: ["Innovation Award", "Best Employer"],
  socialMedia: {
      twitter: "https://twitter.com/IBM",
      linkedIn: "https://www.linkedin.com/company/ibm",
      facebook: "https://www.facebook.com/ibm",
  },
  contactEmail: "contact@ibm.com",
  customerSupport: {
      phone: "+1 (800) IBM-CALL",
      chat: "https://www.ibm.com/support",
  },
  partnerships: ["Red Hat", "Salesforce", "VMware"],
  posts: [
      {
          content: "Explore the future of AI with Watson!",
          imageUrl: ""   },
      {
          content: "Join us at the IBM Cloud Summit!",
          imageUrl: ""   },
  ],
  shortDescription: "IBM is a pioneer in the field of information technology, with a rich history dating back to 1911. The company continues to lead in innovation, providing cutting-edge solutions in cloud computing, AI, and enterprise services.",
},
{
id:7,
  name: "Intel",
  followers: "5M followers",
  logoUrl: "https://www.datacenterknowledge.com/sites/datacenterknowledge.com/files/styles/article_featured_retina/public/2J8DPRY.jpg?itok=rCCZCDld",
  industry: "Semiconductors",
  foundedYear: 1968,
  description: "Intel Corporation is an American multinational semiconductor and technology company. Intel is a leading manufacturer of microprocessors for personal computers and a key player in the semiconductor industry.",
  location: "Santa Clara, California, USA",
  revenue: "$77.9 billion (2021)",
  website: "https://www.intel.com",
  ceo: "Pat Gelsinger",
  employees: 116000,
  products: ["Intel Core", "Xeon", "Intel Evo Platform"],
  stockSymbol: "INTC",
  headquarters: "2200 Mission College Blvd., Santa Clara, CA 95054, USA",
  marketCap: "$200 billion (2021)",
  competitors: ["AMD", "NVIDIA", "Qualcomm"],
  awards: ["Best Semiconductor Company", "Top Innovator"],
  socialMedia: {
      twitter: "https://twitter.com/intel",
      linkedIn: "https://www.linkedin.com/company/intel",
      facebook: "https://www.facebook.com/Intel",
  },
  contactEmail: "contact@intel.com",
  customerSupport: {
      phone: "+1 (408) 765-8080",
      chat: "https://www.intel.com/content/www/us/en/support/contact-support.html",
  },
  partnerships: ["Microsoft", "Dell", "HP"],
  posts: [
      {
          content: "Discover the latest in semiconductor technology!",
          imageUrl: ""     },
      {
          content: "Explore Intel's contributions to AI!",
          imageUrl: ""     },
  ],
  shortDescription: "Intel is a global technology leader in semiconductor manufacturing, shaping the future of computing. With a legacy dating back to 1968, Intel continues to drive innovation in processors and technologies that power our digital world.",
},
{
id:8,
name: "Cisco",
followers: "3M followers",
logoUrl: "https://cdn.britannica.com/90/194590-050-503325E5/building-Cisco-Systems.jpg",
industry: "Networking and Telecommunications",
foundedYear: 1984,
description: "Cisco Systems, Inc. is a multinational technology company specializing in networking hardware, software, and telecommunications equipment. Cisco is a global leader in networking solutions, providing products and services for enterprise and service provider markets.",
location: "San Jose, California, USA",
revenue: "$48 billion (2021)",
website: "https://www.cisco.com",
ceo: "Chuck Robbins",
employees: 77000,
products: ["Cisco Catalyst", "Cisco ASR", "Webex"],
stockSymbol: "CSCO",
headquarters: "170 West Tasman Drive, San Jose, CA 95134, USA",
marketCap: "$215 billion (2021)",
competitors: ["Juniper Networks", "Huawei", "Aruba Networks"],
awards: ["Best Networking Solutions", "Innovation Award"],
socialMedia: {
    twitter: "https://twitter.com/Cisco",
    linkedIn: "https://www.linkedin.com/company/cisco",
    facebook: "https://www.facebook.com/Cisco",
},
contactEmail: "info@cisco.com",
customerSupport: {
    phone: "+1 (800) 553-6387",
    chat: "https://www.cisco.com/c/en/us/support/index.html",
},
partnerships: ["Microsoft", "Google Cloud", "IBM"],
posts: [
    {
        content: "Explore the future of networking with Cisco!",
        imageUrl: ""   },
    {
        content: "Join Cisco's virtual events for IT professionals!",
        imageUrl: ""   },
],
shortDescription: "Cisco is a global leader in networking solutions, providing innovative products and services for a connected world. With a history dating back to 1984, Cisco continues to shape the future of networking technology.",
},
{
id:9,
name: "Oracle",
followers: "6M followers",
logoUrl: "https://files.scmagazine.com/wp-content/uploads/2023/09/0921_oracle.jpg",
industry: "Enterprise Software",
foundedYear: 1977,
description: "Oracle Corporation is an American multinational computer technology corporation that provides software, cloud solutions, and hardware products. Oracle is a major player in the enterprise software market, offering a wide range of applications and database solutions.",
location: "Redwood City, California, USA",
revenue: "$39.1 billion (2021)",
website: "https://www.oracle.com",
ceo: "Safra Catz",
employees: 135000,
products: ["Oracle Database", "Oracle Cloud", "Java"],
stockSymbol: "ORCL",
headquarters: "500 Oracle Parkway, Redwood City, CA 94065, USA",
marketCap: "$213 billion (2021)",
competitors: ["Microsoft", "SAP", "Salesforce"],
awards: ["Top Software Provider", "Innovation Excellence"],
socialMedia: {
    twitter: "https://twitter.com/Oracle",
    linkedIn: "https://www.linkedin.com/company/oracle",
    facebook: "https://www.facebook.com/OracleCorp",
},
contactEmail: "info@oracle.com",
customerSupport: {
    phone: "+1 (800) ORACLE1",
    chat: "https://www.oracle.com/contact",
},
partnerships: ["IBM", "Amazon Web Services", "Cisco"],
posts: [
    {
        content: "Explore the power of Oracle Cloud services!",
        imageUrl: ""    },
    {
        content: "Learn about the latest innovations in Oracle Database!",
        imageUrl: ""    },
],
shortDescription: "Oracle is a leading provider of enterprise software and cloud solutions, empowering businesses with innovative technologies. With a legacy dating back to 1977, Oracle continues to redefine the landscape of information technology.",
},
{
id:10,
name: "Dell",
followers: "4M followers",
logoUrl: "https://8f430952.rocketcdn.me/wp-content/uploads/2021/11/Dell.png",
industry: "Information Technology",
foundedYear: 1984,
description: "Dell Technologies is a multinational technology company that provides a wide range of hardware, software, and services. Dell is known for its innovative products, including laptops, desktops, servers, and storage solutions.",
location: "Round Rock, Texas, USA",
revenue: "$94.2 billion (2021)",
website: "https://www.dell.com",
ceo: "Michael Dell",
employees: 158000,
products: ["Dell XPS", "Dell Latitude", "PowerEdge Servers"],
stockSymbol: "DELL",
headquarters: "One Dell Way, Round Rock, TX 78682, USA",
marketCap: "$55 billion (2021)",
competitors: ["HP Inc.", "Lenovo", "Apple"],
awards: ["Best Laptop Brand", "Innovation Award"],
socialMedia: {
    twitter: "https://twitter.com/Dell",
    linkedIn: "https://www.linkedin.com/company/dell",
    facebook: "https://www.facebook.com/Dell",
},
contactEmail: "info@dell.com",
customerSupport: {
    phone: "+1 (800) 624-9897",
    chat: "https://www.dell.com/support",
},
partnerships: ["Microsoft", "VMware", "Intel"],
posts: [
    {
        content: "Discover the latest Dell XPS series with cutting-edge features!",
        imageUrl: ""  },
    {
        content: "Join Dell's virtual events for technology enthusiasts!",
        imageUrl: ""  },
],
shortDescription: "Dell Technologies is a global leader in information technology, providing innovative solutions for personal and enterprise computing. With a legacy dating back to 1984, Dell continues to shape the future of digital technology.",
},
{
id:11,
name: "HP",
followers: "7M followers",
logoUrl: "https://images.livemint.com/img/2021/11/16/600x338/hp--621x414_1637049509387.jpg",
industry: "Information Technology",
foundedYear: 1939,
description: "HP Inc. is a multinational information technology company that specializes in manufacturing and developing personal computers, printers, and other related products. HP is a trusted brand known for its high-quality technology solutions.",
location: "Palo Alto, California, USA",
revenue: "$56.6 billion (2021)",
website: "https://www.hp.com",
ceo: "Enrique Lores",
employees: 566000,
products: ["HP Pavilion", "HP Spectre", "LaserJet Printers"],
stockSymbol: "HPQ",
headquarters: "1501 Page Mill Road, Palo Alto, CA 94304, USA",
marketCap: "$32 billion (2021)",
competitors: ["Dell", "Lenovo", "Apple"],
awards: ["Best Printer Brand", "Innovation Excellence"],
socialMedia: {
    twitter: "https://twitter.com/HP",
    linkedIn: "https://www.linkedin.com/company/hp",
    facebook: "https://www.facebook.com/HP",
},
contactEmail: "info@hp.com",
customerSupport: {
    phone: "+1 (800) 474-6836",
    chat: "https://support.hp.com/us-en/contact-hp",
},
partnerships: ["Microsoft", "Intel", "Adobe"],
posts: [
    {
        content: "Experience the power of HP laptops with sleek design and performance!",
        imageUrl: ""},
    {
        content: "HP's latest innovations in printing technology – Explore now!",
        imageUrl: ""},
],
shortDescription: "HP Inc. is a leading provider of technology solutions, delivering cutting-edge products for personal and business use. With a history dating back to 1939, HP continues to set new standards in the world of digital innovation.",
},
{
id: 12,
name: "SAP",
followers: "2M followers",
logoUrl: "https://content.fortune.com/wp-content/uploads/2020/11/SAP-Company-Page-Data_Center_07_Steinhauser_.jpg",
industry: "Software",
foundedYear: 1972,
description: "SAP SE is a German multinational software corporation that develops enterprise software solutions for managing business operations and customer relations. SAP is a market leader in enterprise resource planning (ERP) software.",
location: "Walldorf, Baden-Württemberg, Germany",
revenue: "€27.3 billion (2020)",
website: "https://www.sap.com",
ceo: "Christian Klein",
employees: 103023,
products: ["SAP S/4HANA", "SAP Business Suite", "SAP SuccessFactors"],
stockSymbol: "SAP",
headquarters: "Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany",
marketCap: "€148.7 billion (2021)",
competitors: ["Oracle", "Microsoft", "Salesforce"],
awards: ["Best ERP Software", "Innovation in Technology"],
socialMedia: {
    twitter: "https://twitter.com/SAP",
    linkedIn: "https://www.linkedin.com/company/sap",
    facebook: "https://www.facebook.com/SAP",
},
contactEmail: "info@sap.com",
customerSupport: {
    phone: "+49 6227 747474",
    chat: "https://support.sap.com",
},
partnerships: ["Microsoft", "IBM", "Amazon Web Services"],
posts: [
    {
        content: "Explore the latest innovations in SAP S/4HANA for intelligent business operations.",
        imageUrl: "" },
    {
        content: "Join SAP's virtual events for insights into the future of enterprise software.",
        imageUrl: "" },
],
shortDescription: "SAP SE is a global leader in enterprise software, providing innovative solutions to help businesses streamline their operations. With a rich history dating back to 1972, SAP continues to drive digital transformation for organizations worldwide.",
},
{
id: 13,
name: "NVIDIA",
followers: "1M followers",
logoUrl: "https://media.gettyimages.com/id/1494623399/photo/chipmaker-nvidias-valuation-passes-1-trillion-in-market-cap.jpg?s=594x594&w=gi&k=20&c=DZOOdkUKGyjSJcmHgvGO1MZfwqc1hxUVG1BgvN5Al88=",
industry: "Semiconductors",
foundedYear: 1993,
description: "NVIDIA Corporation is an American multinational technology company that designs graphics processing units (GPUs) and system-on-a-chip units (SoCs) for gaming, professional markets, and mobile computing.",
location: "Santa Clara, California, USA",
revenue: "$16.68 billion (2020)",
website: "https://www.nvidia.com",
ceo: "Jensen Huang",
employees: 18907,
products: ["GeForce GPUs", "Quadro GPUs", "NVIDIA Tesla"],
stockSymbol: "NVDA",
headquarters: "2788 San Tomas Expressway, Santa Clara, CA 95051, USA",
marketCap: "$330 billion (2021)",
competitors: ["AMD", "Intel", "Qualcomm"],
awards: ["Best Graphics Card", "Innovation in Technology"],
socialMedia: {
    twitter: "https://twitter.com/nvidia",
    linkedIn: "https://www.linkedin.com/company/nvidia",
    facebook: "https://www.facebook.com/NVIDIA",
},
contactEmail: "info@nvidia.com",
customerSupport: {
    phone: "+1 (408) 486-2000",
    chat: "https://www.nvidia.com/en-us/support/",
},
partnerships: ["Microsoft", "ASUS", "HP Inc."],
posts: [
    {
        content: "Experience stunning graphics and performance with NVIDIA GeForce GPUs.",
        imageUrl: ""    },
    {
        content: "Explore the future of AI with NVIDIA's advanced computing solutions.",
        imageUrl: ""    },
],
shortDescription: "NVIDIA Corporation is a leading provider of graphics processing units (GPUs) and cutting-edge technologies. Founded in 1993, NVIDIA is renowned for its innovations in gaming, professional graphics, and artificial intelligence.",
},
{
id: 14,
name: "VMware",
followers: "1.5M followers",
logoUrl: "https://techcrunch.com/wp-content/uploads/2020/05/GettyImages-474325206.jpg",
industry: "Cloud Computing",
foundedYear: 1998,
description: "VMware, Inc. is an American cloud computing and virtualization technology company. It provides software and services for desktop virtualization, server virtualization, and cloud management.",
location: "Palo Alto, California, USA",
revenue: "$11.8 billion (2020)",
website: "https://www.vmware.com",
ceo: "Raghu Raghuram",
employees: 31000,
products: ["VMware vSphere", "VMware Workstation", "VMware Cloud"],
stockSymbol: "VMW",
headquarters: "3401 Hillview Avenue, Palo Alto, CA 94304, USA",
marketCap: "$74 billion (2021)",
competitors: ["Microsoft", "Citrix", "Red Hat"],
awards: ["Best Virtualization Software", "Innovation in Cloud Computing"],
socialMedia: {
    twitter: "https://twitter.com/VMware",
    linkedIn: "https://www.linkedin.com/company/vmware",
    facebook: "https://www.facebook.com/VMware",
},
contactEmail: "info@vmware.com",
customerSupport: {
    phone: "+1 (877) 486-9273",
    chat: "https://www.vmware.com/support.html",
},
partnerships: ["Dell Technologies", "HPE", "IBM"],
posts: [
    {
        content: "Explore the latest advancements in cloud computing with VMware solutions.",
        imageUrl: ""    },
    {
        content: "Learn how VMware's virtualization technology enhances IT infrastructure efficiency.",
        imageUrl: ""    },
],
shortDescription: "VMware, Inc. is a pioneer in cloud computing and virtualization technology. Founded in 1998, VMware continues to lead the industry with innovative solutions for desktop and server virtualization, and cloud management.",
},
{
id: 15,
name: "Adobe",
followers: "12M followers",
logoUrl: "https://c8.alamy.com/comp/2HA87X4/san-jose-ca-usa-october-17-2021-editorial-use-only-3d-cgi-adobe-signage-logo-on-top-of-glass-building-workplace-computer-software-company-in-h-2HA87X4.jpg",
industry: "Software",
foundedYear: 1982,
description: "Adobe Inc. is an American multinational computer software company. It is best known for its creativity and multimedia software products, including Photoshop, Illustrator, InDesign, Premiere Pro, and more.",
location: "San Jose, California, USA",
revenue: "$12.87 billion (2020)",
website: "https://www.adobe.com",
ceo: "Shantanu Narayen",
employees: 24000,
products: ["Adobe Creative Cloud", "Adobe Document Cloud", "Adobe Experience Cloud"],
stockSymbol: "ADBE",
headquarters: "345 Park Avenue, San Jose, CA 95110-2704, USA",
marketCap: "$282 billion (2021)",
competitors: ["Microsoft", "Autodesk", "Corel"],
awards: ["Best Creative Software", "Innovation in Design"],
socialMedia: {
    twitter: "https://twitter.com/Adobe",
    linkedIn: "https://www.linkedin.com/company/adobe",
    facebook: "https://www.facebook.com/Adobe",
},
contactEmail: "info@adobe.com",
customerSupport: {
    phone: "+1 (800) 833-6687",
    chat: "https://helpx.adobe.com/support.html",
},
partnerships: ["Microsoft", "IBM", "Salesforce"],
posts: [
    {
        content: "Unlock your creative potential with Adobe Creative Cloud.",
        imageUrl: ""   },
    {
        content: "Discover the latest features in Adobe's software for design and digital experiences.",
        imageUrl: ""   },
],
shortDescription: "Adobe Inc. is a leading software company specializing in creativity and multimedia solutions. With a rich history dating back to 1982, Adobe continues to empower individuals and businesses with cutting-edge software products.",
},
{
id: 16,
name: "Accenture",
followers: "9M followers",
logoUrl: "https://static.businessworld.in/article/article_extra_large_image/1631088510_7TUKtV_Accenture_1600x1066_1.jpeg",
industry: "Consulting and Professional Services",
foundedYear: 1989,
description: "Accenture is a global professional services company providing strategy, consulting, digital, technology, and operations services. It is a Fortune Global 500 company, serving clients in more than 120 countries.",
location: "Dublin, Ireland",
revenue: "$44.33 billion (2021)",
website: "https://www.accenture.com",
ceo: "Julie Sweet",
employees: 624000,
services: ["Strategy & Consulting", "Interactive", "Technology", "Operations"],
stockSymbol: "ACN",
headquarters: "1 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland",
marketCap: "$214.4 billion (2021)",
competitors: ["Deloitte", "IBM", "Capgemini"],
awards: ["Best Consulting Firm", "Digital Transformation Excellence"],
socialMedia: {
    twitter: "https://twitter.com/Accenture",
    linkedIn: "https://www.linkedin.com/company/accenture",
    facebook: "https://www.facebook.com/accenture",
},
contactEmail: "info@accenture.com",
customerSupport: {
    phone: "+1 (877) 889-9009",
    chat: "https://www.accenture.com/us-en/contact-us",
},
partnerships: ["Microsoft", "Salesforce", "SAP"],
posts: [
    {
        content: "Explore the latest trends in digital transformation with Accenture.",
        imageUrl: "",
    },
    {
        content: "Learn how Accenture is driving innovation and delivering value to clients worldwide.",
        imageUrl: "",
    },
],
shortDescription: "Accenture is a leading global professional services company that specializes in strategy, consulting, digital, technology, and operations. With a rich history dating back to 1989, Accenture is dedicated to helping clients achieve high performance.",
},
{
id: 17,
name: "Infosys",
followers: "3.5M followers",
logoUrl: "https://www.infosys.com/content/dam/infosys-web/en/about/images/esg-policies.jpg",
industry: "Information Technology and Services",
foundedYear: 1981,
description: "Infosys is a multinational corporation that provides IT consulting and services, including software development, maintenance, and independent validation. It is one of the largest IT services firms globally.",
location: "Bangalore, India",
revenue: "$13.56 billion (2021)",
website: "https://www.infosys.com",
ceo: "Salil Parekh",
employees: 259619,
services: ["Digital Services", "Cloud Services", "AI and Automation"],
stockSymbol: "INFY",
headquarters: "Electronics City, Hosur Road, Bangalore, Karnataka, 560100, India",
marketCap: "$104.2 billion (2021)",
competitors: ["TCS", "Wipro", "Cognizant"],
awards: ["Best IT Services Company", "Excellence in Innovation"],
socialMedia: {
    twitter: "https://twitter.com/Infosys",
    linkedIn: "https://www.linkedin.com/company/infosys",
    facebook: "https://www.facebook.com/Infosys",
},
contactEmail: "support@infosys.com",
customerSupport: {
    phone: "+1 (800) 462-4467",
    chat: "https://www.infosys.com/contact-us/",
},
partnerships: ["Microsoft", "Oracle", "IBM"],
posts: [
    {
        content: "Discover how Infosys is driving digital transformation and innovation in the IT industry.",
        imageUrl: ""
    },
    {
        content: "Explore the latest technologies and solutions offered by Infosys to empower businesses globally.",
        imageUrl: ""
    },
],
shortDescription: "Infosys is a global leader in IT consulting and services, providing innovative solutions for digital transformation. Established in 1981, Infosys is committed to delivering excellence and driving business success for its clients.",
},
{
id: 18,
name: "TCS",
followers: "5.5M followers",
logoUrl: "https://static.toiimg.com/thumb/msid-89135198,width-400,resizemode-4/89135198.jpg",
industry: "Information Technology and Services",
foundedYear: 1968,
description: "Tata Consultancy Services (TCS) is a global leader in IT services, consulting, and business solutions. With a rich history spanning over five decades, TCS is dedicated to delivering innovative and high-quality services to clients worldwide.",
location: "Mumbai, India",
revenue: "$22.17 billion (2021)",
website: "https://www.tcs.com",
ceo: "Rajesh Gopinathan",
employees: 509058,
services: ["Digital Transformation", "Cloud Services", "Analytics"],
stockSymbol: "TCS",
headquarters: "Mumbai, Maharashtra, 400 001, India",
marketCap: "$175.6 billion (2021)",
competitors: ["Infosys", "Wipro", "Cognizant"],
awards: ["Best Employer", "Excellence in Corporate Social Responsibility"],
socialMedia: {
    twitter: "https://twitter.com/TCS",
    linkedIn: "https://www.linkedin.com/company/tata-consultancy-services",
    facebook: "https://www.facebook.com/TataConsultancyServices",
},
contactEmail: "info@tcs.com",
customerSupport: {
    phone: "+91 (22) 6778 9999",
    chat: "https://www.tcs.com/contact-us",
},
partnerships: ["Microsoft", "IBM", "Oracle"],
posts: [
    {
        content: "Explore the latest advancements in technology and business solutions with TCS.",
        imageUrl: "" },
    {
        content: "Learn how TCS is driving digital innovation and transforming businesses across industries.",
        imageUrl: "" },
],
shortDescription: "Tata Consultancy Services (TCS) is a leading global IT services and consulting company, known for its commitment to excellence and innovation. With a vast range of services, TCS empowers organizations to thrive in the digital era.",
},
{
id: 19,
name: "Wipro",
followers: "2.5M followers",
logoUrl: "https://www.shutterstock.com/image-photo/bucharest-romania-july-10-2023-260nw-2335935755.jpg",
industry: "Information Technology and Services",
foundedYear: 1945,
description: "Wipro Limited is a multinational IT services company that provides consulting, business process outsourcing, and digital solutions to clients around the world. With a legacy of excellence, Wipro is dedicated to delivering value and innovation.",
location: "Bangalore, India",
revenue: "$8.4 billion (2021)",
website: "https://www.wipro.com",
ceo: "Thierry Delaporte",
employees: 200000,
services: ["Digital Transformation", "IT Consulting", "Outsourcing"],
stockSymbol: "WIPRO",
headquarters: "Sarjapur Main Road, Doddakannelli, Bangalore, Karnataka, 560035, India",
marketCap: "$34.5 billion (2021)",
competitors: ["TCS", "Infosys", "Accenture"],
awards: ["Best IT Services Company", "Global Sustainability Leadership Award"],
socialMedia: {
    twitter: "https://twitter.com/Wipro",
    linkedIn: "https://www.linkedin.com/company/wipro",
    facebook: "https://www.facebook.com/WiproTechnologies",
},
contactEmail: "info@wipro.com",
customerSupport: {
    phone: "+1 (800) 633-7638",
    chat: "https://www.wipro.com/contact/",
},
partnerships: ["Microsoft", "SAP", "Cisco"],
posts: [
    {
        content: "Discover how Wipro is driving digital transformation and innovation across industries.",
        imageUrl: " "  },
    {
        content: "Explore Wipro's commitment to sustainability and social responsibility.",
        imageUrl: " "  },
],
shortDescription: "Wipro Limited is a global leader in IT services, known for its diverse range of solutions and commitment to sustainability. With a history dating back to 1945, Wipro continues to shape the future of technology and business.",
},
{
id: 20,
name: "Capgemini",
followers: "4.5M followers",
logoUrl: "https://static.javatpoint.com/company/images/capgemini-company.png",
industry: "Information Technology and Services",
foundedYear: 1967,
description: "Capgemini is a global leader in consulting, technology services, and digital transformation. With a focus on innovation and collaboration, Capgemini empowers organizations to achieve their business goals and stay ahead in a rapidly evolving digital landscape.",
location: "Paris, France",
revenue: "$22.9 billion (2021)",
website: "https://www.capgemini.com",
ceo: "Aiman Ezzat",
employees: 300000,
services: ["Consulting", "Technology Services", "Digital Transformation"],
stockSymbol: "CAP",
headquarters: "Paris, Île-de-France, 75008, France",
marketCap: "$30.4 billion (2021)",
competitors: ["Accenture", "IBM", "TCS"],
awards: ["Best IT Services Company", "Innovation Excellence Award"],
socialMedia: {
    twitter: "https://twitter.com/Capgemini",
    linkedIn: "https://www.linkedin.com/company/capgemini",
    facebook: "https://www.facebook.com/CapgeminiOfficial",
},
contactEmail: "info@capgemini.com",
customerSupport: {
    phone: "+33 (0)1 47 54 50 00",
    chat: "https://www.capgemini.com/contact/",
},
partnerships: ["Microsoft", "Salesforce", "SAP"],
posts: [
    {
        content: "Explore the latest insights and trends in digital transformation with Capgemini.",
        imageUrl: "",
    },
    {
        content: "Discover how Capgemini is driving innovation and creating value for clients worldwide.",
        imageUrl: "",
    },
],
shortDescription: "Capgemini is a global consulting and technology services company that enables organizations to navigate the complexities of the digital world. With a rich history and a commitment to excellence, Capgemini continues to lead in the era of digital transformation.",
},
{
id: 21,
name: "Cognizant",
followers: "6.5M followers",
logoUrl: "https://akm-img-a-in.tosshub.com/businesstoday/images/story/202306/edl1-ofvaaahmlq-sixteen_nine.jpg?size=948:533",
industry: "Information Technology and Services",
foundedYear: 1994,
description: "Cognizant is a multinational technology company that provides a range of IT services, including consulting, digital strategy, and business process outsourcing. With a customer-centric approach, Cognizant helps clients achieve operational excellence and drive innovation.",
location: "Teaneck, New Jersey, USA",
revenue: "$17.6 billion (2021)",
website: "https://www.cognizant.com",
ceo: "Brian Humphries",
employees: 300000,
services: ["Digital Transformation", "IT Consulting", "Outsourcing"],
stockSymbol: "CTSH",
headquarters: "Teaneck, NJ 07666, USA",
marketCap: "$67.2 billion (2021)",
competitors: ["Accenture", "TCS", "Infosys"],
awards: ["Best Workplace", "Excellence in Customer Service"],
socialMedia: {
    twitter: "https://twitter.com/Cognizant",
    linkedIn: "https://www.linkedin.com/company/cognizant",
    facebook: "https://www.facebook.com/Cognizant",
},
contactEmail: "info@cognizant.com",
customerSupport: {
    phone: "+1 (888) 937-3277",
    chat: "https://www.cognizant.com/contact-us",
},
partnerships: ["Amazon Web Services", "Google Cloud", "Microsoft"],
posts: [
    {
        content: "Stay updated with Cognizant's latest solutions and insights in technology and business.",
        imageUrl: "",
    },
    {
        content: "Explore how Cognizant is transforming industries and driving digital innovation.",
        imageUrl: "",
    },
],
shortDescription: "Cognizant is a global leader in technology services, known for its innovative solutions and commitment to client success. With a focus on digital transformation, Cognizant empowers businesses to thrive in the digital age.",
},

];

export default itCompanies;